name: pocket_tasks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

flutter:
  uses-material-design: true

fonts:
     - family: Open Sans Hebrew
       fonts:
         - asset: fonts/Open Sans Hebrew Regular.ttf